monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: stream
            path: "%kernel.logs_dir%/console_%kernel.environment%.log"
            level: debug
            channels: ["!event"]
